name: CI

on:
  push:
    branches:
      - master
      - master2
  pull_request:
    branches:
      - master
      - master2

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3


      - name: Lint with ruff
        run: |
          
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          ruff --format=github --target-version=py37 .
      - name: Run
        run: python main.py
      - name: Test
        run: python test.py
