name: CI

on:
  push:
    branches:
      - master
      - master2
  pull_request:
    branches:
      - master
      - master2

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          pip install pylint
          pip install coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: pylint
        run:
          pylint main.py
      - name: Run
        run: pytest test.py
      - name: Test
        run: coverage run -m pytest test.py
